New DNS Seeders for DOGE
dogecoin/dogecoin pull request #1669
Opened 2021-01-29 23:35 UTC by carsenk

Courtesy of https://denarius.io Denarius (D) community we are providing Dogecoin some DNS peer seeders, this PR includes the seeders hard coded in

```
veryseed.denarius.pro
muchseed.denarius.pro
```

2021-01-29 23:55 UTC, CircuitBreaker88 commented
Nice!

2021-01-30 12:44 UTC, rnicoll commented
How did you test these work? Same question seed2. So:

```
jrn@testnet-node:~$ dig @ns2.multidoge.org seed2.multidoge.org

; <<>> DiG 9.11.3-1ubuntu1.13-Ubuntu <<>> @ns2.multidoge.org seed2.multidoge.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11463
;; flags: qr aa rd; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;seed2.multidoge.org.           IN      A

;; ANSWER SECTION:
seed2.multidoge.org.    600     IN      A       31.165.17.142
seed2.multidoge.org.    600     IN      A       91.86.219.71
seed2.multidoge.org.    600     IN      A       73.167.72.250
seed2.multidoge.org.    600     IN      A       71.161.223.193

;; Query time: 81 msec
;; SERVER: 63.34.247.220#53(63.34.247.220)
;; WHEN: Sat Jan 30 13:42:36 CET 2021
;; MSG SIZE  rcvd: 177
```

That's what I'd expect. On veryseed at least:

```
$ dig @veryseed.denarius.pro veryseed.denarius.pro

; <<>> DiG 9.11.3-1ubuntu1.13-Ubuntu <<>> @veryseed.denarius.pro veryseed.denarius.pro
; (10 servers found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Fairly certain the nameserver and address can't be the same, because then you're trying to resolve the IP of the nameserver by querying itself, and that confuses the hell out of things.

2021-01-30 17:31 UTC, carsenk commented
@rnicoll 

```
dig -t A veryseed.denarius.pro

; <<>> DiG 9.16.1-Ubuntu <<>> -t A veryseed.denarius.pro
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3518
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;veryseed.denarius.pro.        IN    A

;; ANSWER SECTION:
veryseed.denarius.pro.    3024    IN    A    138.68.244.109
veryseed.denarius.pro.    3024    IN    A    93.114.128.120
veryseed.denarius.pro.    3024    IN    A    87.100.205.39
veryseed.denarius.pro.    3024    IN    A    73.221.48.43
veryseed.denarius.pro.    3024    IN    A    78.56.87.65
veryseed.denarius.pro.    3024    IN    A    206.172.73.120

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sat Jan 30 09:29:24 PST 2021
;; MSG SIZE  rcvd: 14
```

```
dig -t NS veryseed.denarius.pro

; <<>> DiG 9.16.1-Ubuntu <<>> -t NS veryseed.denarius.pro
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64243
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;veryseed.denarius.pro.        IN    NS

;; ANSWER SECTION:
veryseed.denarius.pro.    6894    IN    NS    verydoge.denarius.pro.

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sat Jan 30 09:28:07 PST 2021
;; MSG SIZE  rcvd: 73
```
verydoge.denarius.pro hosts the name service for veryseed.denarius.pro

2021-01-31 00:37 UTC, patricklodder requested changes
Please remove unnecessary comments.

2021-01-31 00:37 UTC, patricklodder commented on src/chainparams.cpp
> +        vSeeds.push_back(CDNSSeedData("multidoge.org", "seed2.multidoge.org")); // Seeders are dead
according to my checks over the past 24h, this seeder is not dead. The community may want to put some downtime detection on individual seeders though.

2021-01-31 00:37 UTC, patricklodder commented on src/chainparams.cpp
> +        vSeeds.push_back(CDNSSeedData("suchseed.denarius.pro", "suchseed.denarius.pro")); //New working seeders Courtesy of Denarius (D) denarius.io Such D Much Wow
Can we remove the comment?

2021-01-31 02:04 UTC, carsenk commented on src/chainparams.cpp
> +        vSeeds.push_back(CDNSSeedData("suchseed.denarius.pro", "suchseed.denarius.pro")); //New working seeders Courtesy of Denarius (D) denarius.io Such D Much Wow
Removed all :)

2021-01-31 02:04 UTC, carsenk commented
Removed Comments. To the moon!

2021-01-31 17:44 UTC, patricklodder commented
- [x] Stability of DNS server confirmed over the past 48h (will still continue)
- [x] Crawler does not misbehave 
   
Per this: https://github.com/dogecoin/dogecoin/blob/master/doc/dnsseed-policy.md
- [ ] Could you please confirm that you comply to "4. Any logging of DNS queries should be only that which is necessary for the operation of the service or urgent health of the Dogecoin network and **must not be retained longer than necessary nor disclosed to any third party**."?
- [ ] Per "6. Operators are encouraged, but not required, to publicly document the details of their operating practices." Do you have such documentation and/or is your crawler open-source?
- [ ] 7. Please provide an email address

Once that is done, I'm good.

2021-01-31 21:29 UTC, buzzkillb commented
> 
> 
>     * [x]  Stability of DNS server confirmed over the past 48h (will still continue)
> 
>     * [x]  Crawler does not misbehave
> 
> 
> Per this: https://github.com/dogecoin/dogecoin/blob/master/doc/dnsseed-policy.md
> 
>     * [ ]  Could you please confirm that you comply to "4. Any logging of DNS queries should be only that which is necessary for the operation of the service or urgent health of the Dogecoin network and **must not be retained longer than necessary nor disclosed to any third party**."?
> 
>     * [ ]  Per "6. Operators are encouraged, but not required, to publicly document the details of their operating practices." Do you have such documentation and/or is your crawler open-source?
> 
>     * [ ]  7. Please provide an email address
> 
> 
> Once that is done, I'm good.

- Logging is whatever the stats dump is in the folder during crawling to run the seeder. 3rd parties will never be given access to the servers or share the info out.
- Crawler is open source fork of Sipa but easier to configure, https://github.com/team-exor/generic-seeder
- buzz@denarius.io

2021-01-31 21:47 UTC, carsenk commented
> * Logging is whatever the stats dump is in the folder during crawling to run the seeder. 3rd parties will never be given access to the servers or share the info out.
> * Crawler is open source fork of Sipa but easier to configure, https://github.com/team-exor/generic-seeder
> * [buzz@denarius.io](mailto:buzz@denarius.io)

^^^

2021-02-01 15:49 UTC, mxaddict approved these changes

2021-02-01 15:52 UTC, arulnick commented
I'm just curious why there isn't a requirement for use of OpenSSL/SHA 256 connections?  Mostly just wondering/devils advocate. Sorry to hijack just a question that came to my mind.

2021-02-01 16:16 UTC, patricklodder commented
> I'm just curious why there isn't a requirement for use of OpenSSL/SHA 256 connections? Mostly just wondering/devils advocate. Sorry to hijack just a question that came to my mind.

On DNS? Because I am not at all sure that with our `getaddrinfo()`-dependent implementation we can actually do DNS over TLS. Is worth looking into, but not the 1.14.3 release target. Be my guest to do the research on how it could be implemented and we can look at that in a subsequent release.

2021-02-01 16:20 UTC, patricklodder approved these changes
ACK on the code.
ACK on compliance.

2021-02-01 16:25 UTC, langerhans approved these changes
ACK

2021-02-01 17:00 UTC, merged

2021-02-01 19:17 UTC, bruidbarrett commented
@langerhans I have a very important question regarding the langerhans dogecoin wallet, I messaged you on twitter about it and if there is a good way to contact you please let me know or email me, bruidbarrett@gmail.com. it is VERY IMPORTANT.

2021-02-01 19:20 UTC, langerhans commented
@bruidbarrett Ping me on Discord, but believe, it's currently VERY IMPORTANT for everyone...

2021-02-01 19:21 UTC, bruidbarrett commented
What is your discord?

2021-02-01 19:22 UTC, bruidbarrett commented
@langerhans what is your discord? Sorry I am sure you are busy man!

2021-02-01 19:25 UTC, langerhans commented
I'm on the Dogecoin discord. langerhans#2409. Ping me there.

2021-02-01 20:12 UTC, rnicoll commented
Thank you!