1.21 Scrypt algorithm
dogecoin/dogecoin pull request #1828
Opened 2021-04-17 20:38 UTC by rnicoll

2021-04-17 20:38 UTC, rnicoll commented
Opening this early so I can track what I'm up to

2021-05-20 10:58 UTC, rnicoll commented
Addresses #1793

2021-05-23 14:02 UTC, andrp92 commented
@rnicoll FYI, there are some conflicts with src/pow.cpp

2021-05-23 17:27 UTC, rnicoll commented
@andrp92 Seen it! I've broken a few parts of this into smaller PRs, which I need to figure out Travis timeouts on, but in theory the plan is we'll merge the smaller parts then rebase this, and I'll resolve the conflicts then.

2021-05-23 17:53 UTC, andrp92 commented
Sounds perfect 👌

2021-05-31 20:42 UTC, rnicoll commented on src/chainparams.cpp
> +        consensus.powLimit = uint256S("00000fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"); // ~uint256(0) >> 20;
```suggestion
        consensus.powLimit = uint256S("0x00000fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"); // ~uint256(0) >> 20;
```

2021-05-31 20:42 UTC, rnicoll commented on src/chainparams.cpp
> +        consensus.powLimit = uint256S("00000fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"); // ~uint256(0) >> 20;
```suggestion
        consensus.powLimit = uint256S("0x00000fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"); // ~uint256(0) >> 20;
```

2021-05-31 20:42 UTC, rnicoll commented on src/chainparams.cpp
> +        consensus.powLimit = uint256S("0000f77ae0000000000000000000000000000000000000000000000000000000");
```suggestion
        consensus.powLimit = uint256S("0x0000f77ae0000000000000000000000000000000000000000000000000000000");
```

2021-06-02 00:33 UTC, patricklodder requested changes

2021-06-02 09:59 UTC, rnicoll commented on src/Makefile.am
> +libbitcoinconsensus_la_CPPFLAGS = $(AM_CPPFLAGS) -I$(builddir)/obj -I$(srcdir)/secp256k1/include -DBUILD_BITCOIN_INTERNAL $(SSL_CFLAGS)
Seems to work without, once I realised I needed all of the later commits (as in, it won't fully work until AuxPoW is in), have removed.

2021-06-02 09:59 UTC, rnicoll commented on src/net_processing.cpp
> +        // XXX: Decide how to handle alert migration in Dogecoin and either make this a Dogecoin
Done https://github.com/dogecoin/dogecoin/issues/2231

2021-06-02 10:00 UTC, rnicoll commented on test/functional/rpc_dumptxoutset.py
> +            print(str(digest))
Done

2021-06-02 10:01 UTC, rnicoll commented on src/test/miner_tests.cpp
> +    {0, 0x0002bb2c}, {1, 0x001a9616},
Bitcoin Core now asks for 110 blocks ( https://github.com/bitcoin/bitcoin/blob/master/src/test/miner_tests.cpp#L223 ) so I've added these to match.

2021-06-02 21:44 UTC, patricklodder approved these changes
ACK. Code reviewed, syncs until 158000 for me on testnet.

2021-06-02 21:45 UTC, merged