Improve the efficiency by replace push_back with emplace_back
dogecoin/dogecoin pull request #1930
Opened 2021-05-14 19:20 UTC by bingoko

Improve the Dogecoin core efficiency without any major change.

2021-05-14 19:27 UTC, Cyclic commented
> Improve the Dogecoin core efficiency without any major change.

“Copying of the constructor doesn’t take place while using the emplace_back() function. The cost due to the copying of elements is high.”

2021-05-14 20:19 UTC, huy-springlabs submitted a review, later dismissed

2021-05-14 22:08 UTC, Tracachang submitted a review, later dismissed

2021-05-15 07:47 UTC, rnicoll commented
Very cautious that the semantics of the two are different, and while typically yes the one which doesn't copy the object will be faster, we'd need to verify the original object isn't then reused/modified elsewhere in ways which would cause problems.

2021-05-18 22:36 UTC, l4p4 commented
As complement of @rnicoll, be careful with this change; For more detail: https://stackoverflow.com/questions/4303513/push-back-vs-emplace-back

It is necessary to carry out tests, verifying all calls in the code. But I don't see that it brings any significant performance, it just reduces the possibilities in the long run and can cause issues

2021-05-24 02:13 UTC, nooperation commented on src/wallet/wallet.cpp
> +                vCoins.emplace_back(COutput(pcoin, i, nDepth, fSpendableIn, fSolvableIn));
`vCoins.emplace_back(COutput(pcoin, i, nDepth, fSpendableIn, fSolvableIn));`

This is a good place to show why you can't just simply find and replace all instances of `push_back` with `emplace back`. This is still allocating an entire temporary COutput object **A** to pass to `emplace_back`. Another COutput object is allocated for vCoins itself, moving/copying the contents of the temporary **A** object to itself. This is pretty much the same thing that push_back is doing so this solves nothing

However, consider the following instead:
`
vCoins.emplace_back(pcoin, i, nDepth, fSpendableIn, fSolvableIn);
`

Notice how even visually you're not allocating a temporary object to pass to `emplace_back`? This is where `emplace_back` begins to shine, but you will have to handle these changes on a case by case basis to make sure you're actually reducing allocations and not just adding more work

Here's a snippet of code you can play around with to see it in action: http://cpp.sh/2vzu5

2021-05-24 09:14 UTC, rnicoll commented
Going to close and re-open to re-run CI.

2021-05-24 21:10 UTC, rnicoll requested changes
Appears to not compile. Needs to pass all tests on Travis before we'd consider it, and honestly very cautious this introduces risk for undefined reward.

2021-05-25 10:51 UTC, bingoko commented
> Appears to not compile. Needs to pass all tests on Travis before we'd consider it, and honestly very cautious this introduces risk for undefined reward.

The problem is about couldn't find the emplace_back func in std::vector in the Travis server. It could be the version of C++ or OS system that we used are different.

2021-05-25 20:26 UTC, patricklodder commented
> The problem is about couldn't find the emplace_back func in std::vector in the Travis server. It could be the version of C++ or OS system that we used are different.

Travis builds from `depends/`, as will be done on the gitian builds we need to build auditable binaries from. So it is very important that Travis passes.

2021-05-26 22:36 UTC, jimmyt1988 commented
Perhaps you could provide data of before and after. Perhaps at n=5 on all test cases you can think of that prove your performance gains would provide sufficient proof of gains? :). Lab coat anyone?

2022-07-21 14:39 UTC, patricklodder commented
I'm re-configuring this PR to go against `1.14.7-dev`. I've now re-set the base 3 times, which is fine, however, for this to become mergable, it needs to pass tests. There will also be merge conflicts when this gets rebased (which it must.)

Perhaps an easier approach that doesn't create a lot of merge conflicts would be to:

1. create a benchmark in `src/bench` that executes a function where we think this would be beneficial for performance
2. separately modify the function to use `emplace_back` on top, so that we have 2 metrics.

@bingoko would that be something you'd be willing to pick up?

2023-12-21 21:03 UTC, closed without merging