Avoid &foo[0] on C-Style arrays
dogecoin/dogecoin pull request #1986
Opened 2021-05-22 11:29 UTC by itseasy21

Confusing as some parts of the class use redundant operators and other parts do not.

2021-05-24 21:01 UTC, kalvdans requested changes

2021-05-24 21:01 UTC, kalvdans commented on .github/ISSUE_TEMPLATE.md
> -
Revert this unrelated change in issue templates.

2021-05-25 22:50 UTC, rnicoll commented
I've switched the base to the 1.14.4-dev branch we're working on. Can you rebase please? Try:

git fetch origin
git rebase -i origin/1.14.4-dev

It will then bring up an editor. If you remove the 2 commits before the one you want. Please check the result then force push it, and it should just change the document. Thank you!

2021-08-15 00:37 UTC, chromatic commented
@itseasy21 Looks like there's still an extra commit in here. Would you mind rebasing again to remove the commit with the title "issue template updated to prevent spam in repository"? Thanks!

2021-11-16 20:04 UTC, rnicoll commented
Dug this out - I can rebase it, but I think main question is for 1.14.x are we okay taking on a change which will add conflicts on merges? I don't see us doing major merges from Bitcoin to the branch, so probably okay, just debatable on value?

2021-11-16 20:08 UTC, patricklodder commented
> probably okay, just debatable on value?

Did Bitcoin Core do anything with these?

2021-11-18 05:36 UTC, kalvdans submitted a review, later dismissed
Seems to be equivalent to what was before.

2022-10-09 14:59 UTC, chromatic commented
I compared this code against what's in Bitcoin's main branch, and Bitcoin has all of these changes now. Given that this is a small PR, the code reads much better this way (it's a small change but I'd have to stop and read the code very carefully to figure out *why* it was written the previous way), I'm fine with this. I'll pull and test before giving a complete review.

2022-10-09 15:47 UTC, chromatic commented
Code compile and passes tests for me.

I think there are some extra commits here, so @itseasy21 if you want to rebase on 1.14.7-dev (and include only the code changes and not the commits deleting GitHub issue templates), I can do a final review.

2022-10-10 00:08 UTC, itseasy21 commented
@chromatic should be good to go now..

2022-10-10 05:26 UTC, chromatic approved these changes
All tests pass for me, and the benefit in clearer code makes up for the very low risk of rebase/cherry-pick errors.

2022-10-10 06:09 UTC, kalvdans approved these changes

2022-10-10 07:43 UTC, patricklodder approved these changes
ACK - tested on `x86_64-apple-darwin21.6.0` w/ Apple's `clang-1400.0.29.102`

2022-10-11 18:07 UTC, merged