CPureBlockHeader
dogecoin/dogecoin pull request #2284
Opened 2021-06-09 16:37 UTC by mmicael1

2021-06-09 17:47 UTC, mmicael1 commented
@rnicoll  the CI is not running anymore...

2021-06-09 17:54 UTC, mmicael1 commented
hum `dogecoind: chainparams.cpp:122: CMainParams::CMainParams(): Assertion `consensus.hashGenesisBlock == uint256S("0x1a91e3dace36e2be3bf030a65679fe821aa1d6ef92e7c9902eb318182c355691")' failed.`

2021-06-09 19:38 UTC, rnicoll commented
> 
> 
> hum
> 
> `dogecoind: chainparams.cpp:122: CMainParams::CMainParams(): Assertion consensus.hashGenesisBlock == uint256S("0x1a91e3dace36e2be3bf030a65679fe821aa1d6ef92e7c9902eb318182c355691")' failed.`

Guessing, but suspect it's ended up with a post-AuxPoW version number in the genesis block, or something. I'll take a look in a minute.

2021-06-11 22:43 UTC, rnicoll reviewed
Very quick review of a few points.

2021-06-11 22:43 UTC, rnicoll commented on src/dogecoin.cpp
> +#include <util/system.h>
Probably don't need these changes?

2021-06-11 22:43 UTC, rnicoll commented on src/pow.cpp
> +#include <util/system.h>
Also not needed yet, I think?

2021-06-11 22:43 UTC, rnicoll commented on src/protocol.cpp
> +        // return ServiceFlags(NODE_NETWORK_LIMITED | NODE_WITNESS);
I think this needs to be its own PR so we can revert it individually later, I'll sort that.

2021-06-11 22:43 UTC, rnicoll commented on src/rpc/blockchain.cpp
> +#include <rpc/rawtransaction.h>
Is this used in this PR?

2021-06-11 22:43 UTC, rnicoll commented on src/test/dogecoin_tests.cpp
> +#include <chain.h>
Again is this needed in this PR?

2021-06-11 23:43 UTC, rnicoll commented
Rebased #1974 on top of this (in a private branch) and sync works, so that's good!

2021-06-12 03:27 UTC, mmicael1 commented
@rnicoll all good!

2021-06-12 14:24 UTC, mmicael1 commented
NodeContext commits remove as its part of another PR

2021-07-12 07:22 UTC, rnicoll commented
@micaelmalta Can you do a rebase of this onto 1.21-dev now, please, as we've got the Cirrus CI fixes in?

2021-07-12 10:34 UTC, micaelmalta commented
```
==> Downloading https://dl.bintray.com/homebrew/mirror/boost_1_75_0.tar.bz2
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "boost"
Download failed: https://dl.bintray.com/homebrew/mirror/boost_1_75_0.tar.bz2
```
👎

2021-07-20 20:40 UTC, patricklodder requested changes
Generic changes I'd like to see:
1. Update copyright statement for each file newly introduced, to make sure we do not erroneously assign copyright to people that didn't create those files. (i.e. Add a Dogecoin Core Developers copyright line, those can be 2014-2021)
2. Remove all code that does not touch CPureBlockHeader. I think the full set can be reverted with:

```
git checkout 1.21-dev -- src/chainparams.h
git checkout 1.21-dev -- src/init.cpp
git checkout 1.21-dev -- src/miner.h
git checkout 1.21-dev -- src/protocol.cpp
git checkout 1.21-dev -- src/qt/test/wallettests.cpp
git checkout 1.21-dev -- src/rpc/mining.cpp
git checkout 1.21-dev -- src/rpc/rawtransaction.cpp
git checkout 1.21-dev -- src/test/merkle_tests.cpp
git checkout 1.21-dev -- src/test/util/setup_common.cpp
git checkout 1.21-dev -- src/test/util/setup_common.h
git checkout 1.21-dev -- src/wallet/context.h
git checkout 1.21-dev -- src/wallet/rpcwallet.cpp
git checkout 1.21-dev -- test
git rm src/rpc/rawtransaction.h
```

I have added more comments inline.

2021-07-20 20:51 UTC, rnicoll commented on src/miner.cpp
> +    const int32_t nVersion = 4;
ComputeBlockVersion is used for BIP9. We hard-code so there's no risk of BIP9 versions being used.

2021-07-20 21:01 UTC, patricklodder commented on src/miner.cpp
> +    const int32_t nVersion = 4;
How does that then impact tests pre-auxpow, pre-strict dersig and pre-csv?

2021-09-05 10:29 UTC, rnicoll commented on src/miner.cpp
> +    const int32_t nVersion = 4;
There are test impacts, yes. I'll highlight them in a second.

2021-09-09 17:37 UTC, patricklodder commented
This was cleaned up by @rnicoll in #2547, which has been merged. Thank you!

2021-09-09 17:37 UTC, closed without merging