Change key derivation path to be correct for Dogecoin
dogecoin/dogecoin pull request #2355
Opened 2021-07-01 08:02 UTC by rnicoll

Needs tests updated and needs to handle pre-1.14.4 wallets having the wrong derivation path.

2021-07-01 08:06 UTC, rnicoll commented
It _looks_ like Bitcoin Core hard coded every path to mainnet (didn't understand testnet derivation), so already contains the derivation path in the wallet.dat. Basically consider this an issue raised for me to dig through.

2021-07-01 22:52 UTC, AbcSxyZ commented
Certainly interesting information to add to the documentation.

Was looking once how to retrieve keys from mnemonic phrase, this information was needed. Could be useful for some situation :+1:

2021-08-23 05:10 UTC, chalermchai29 requested changes

2021-08-23 05:10 UTC, chalermchai29 commented on src/wallet/scriptpubkeyman.cpp
> -    // Mainnet derives at 0', testnet and regtest derive at 1'
// Mainnet derives at 3', testnet and regtest derive at 1'
    if (Params().IsTestChain()) {
        desc_prefix += "/1'";
    } else {
        desc_prefix += "/3'";

2021-08-23 05:10 UTC, chalermchai29 commented on src/wallet/scriptpubkeyman.cpp
>      if (Params().IsTestChain()) {
if (Params().IsTestChain()) {
        desc_prefix += "/1'";
    } else {
        desc_prefix += "/3'";
    }

    std::string internal_path = m_internal ? "/1" : "/0";

2021-08-23 05:10 UTC, chalermchai29 commented on test/functional/wallet_hd.py
> -                assert_equal(hd_info["hdkeypath"], "m/0'/0'/" + str(i) + "'")
assert_equal(hd_info["hdkeypath"], "m/0'/3'/" + str(i) + "'")

2021-08-23 05:10 UTC, chalermchai29 commented on test/functional/wallet_hd.py
>              if self.options.descriptors:
if self.options.descriptors:
                assert_equal(hd_info["hdkeypath"], "m/44'/1'/0'/0/" + str(i))

2021-08-23 05:10 UTC, chalermchai29 commented on test/functional/wallet_hd.py
>              if self.options.descriptors:
if self.options.descriptors:

2022-10-08 11:06 UTC, patricklodder commented
Fixed with #2977

2022-10-08 11:06 UTC, closed without merging