Fix FreeBSD scrypt compilation (#2475)
dogecoin/dogecoin pull request #2481
Opened 2021-08-21 18:03 UTC by chromatic

This commit unifies src/crypto/scrypt.h with the version in the 1.21-dev
branch.

Note that while the header guard defined in this file has changed from
`SCRYPT_H` to `BITCOIN_CRYPTO_SCRYPT_H`, the former does not appear in
the codebase on this branch at all, so that change should also be safe.

2021-08-21 18:37 UTC, patricklodder requested changes
Also needs update of `scrypt.cpp` because:
- there are encoder/decoders there too, and
- signature of `scrypt_detect_sse2()` changed from void to returning a string here but not there.

2021-08-21 18:52 UTC, swagile1 commented
Will fix. I thought it looked too easy!

2021-08-22 04:05 UTC, patricklodder commented
Before I do a final review and start testing this on FreeBSD, it would be perfect if in `src/init.cpp` you could replace the current call to `scrypt_detect_sse2()` on line 1223 with:

```
    std::string sse2detect = scrypt_detect_sse2();
    LogPrintf("%s\n", sse2detect);
```

and cast the call in `src/test/scrypt_tests.cpp` on line 17 to a void by prepending `(void)` to the call of that function.

2021-08-22 04:18 UTC, chromatic commented
Done. I couldn't find any other calls than those two, so I think this latest push should clear up all the type errors I missed when I compiled locally.

2021-08-23 05:14 UTC, chalermchai29 requested changes
* Copyright 2009 Colin Percival, 2011 ArtForz, 2012-2013 pooler
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * This file was originally written by Colin Percival as part of the Tarsnap
 * online backup system.
 */

#include <crypto/scrypt.h>
#include <crypto/hmac_sha256.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
	@@ -44,6 +44,7 @@
#endif
#endif

#ifndef __FreeBSD__
static inline uint32_t be32dec(const void *pp)
{
	const uint8_t *p = (uint8_t const *)pp;
	@@ -60,6 +61,8 @@ static inline void be32enc(void *pp, uint32_t x)
	p[0] = (x >> 24) & 0xff;
}

#endif

2021-08-28 17:34 UTC, chromatic commented
@patricklodder I've force pushed a minimal commit now.

2021-08-28 17:37 UTC, patricklodder commented
Thank you! I'm testing compilation today

2021-08-28 22:00 UTC, patricklodder commented
Build on FreeBSD is currently failing with:

```
libtool: link: c++ -std=c++11 -Wstack-protector -fstack-protector-all -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -Wno-self-assign -Wno-unused-local-typedef -Wno-deprecated-register -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -pie -o dogecoind dogecoind-bitcoind.o -pthread  libdogecoin_server.a libdogecoin_common.a univalue/.libs/libunivalue.a libdogecoin_util.a libdogecoin_consensus.a crypto/libdogecoin_crypto.a leveldb/libleveldb.a leveldb/libmemenv.a secp256k1/.libs/libsecp256k1.a -L/usr/local/lib -lboost_system -lboost_filesystem -lboost_program_options -lboost_thread -lboost_chrono -lssl -lcrypto -levent_pthreads -levent -pthread
/usr/bin/ld: crypto/libdogecoin_crypto.a(libdogecoin_crypto_a-scrypt.o): relocation R_X86_64_TPOFF32 against `a local symbol' can not be used when making a shared object; recompile with -fPIC
crypto/libdogecoin_crypto.a: could not read symbols: Bad value
c++: error: linker command failed with exit code 1
```

2021-08-29 14:59 UTC, patricklodder commented
Made it compile with: `./configure --disable-wallet --without-libs --disable-hardening`

I'll look into what we can fix re: hardening when I work through the rest of the FreeBSD install instructions the coming week.

2021-08-29 15:00 UTC, patricklodder approved these changes
ACK. This takes away the scrypt errors regarding built-in encoders/decoders. Tested on FreeBSD w/ Intel x86_64.

2021-08-29 15:01 UTC, merged