Mark getauxblock RPC command as deprecated
dogecoin/dogecoin pull request #2565
Opened 2021-09-12 17:44 UTC by chromatic

Addresses #2300 .

The remaining mentions of this command are all in error messages or QA tests, so I haven't removed them. I could find no other documentation or non-code mention of this command.

The release notes for the next version (1.14.5?) should include a line about this deprecation.

2021-09-12 18:11 UTC, patricklodder commented
The alternative needs to be described. Did anyone test the alternative?

2021-09-12 18:18 UTC, chromatic commented
I don't see that the alternatives actually exist yet on either the 1.14.5-dev or 1.21-dev branches , so this PR *may* be getting ahead of things.

2021-09-12 18:32 UTC, patricklodder commented
The funniest thing is that #1587 removed the alternative (`createauxblock` and `submitauxblock`) for 1.14, so I'd recommend to:

1. Only depreciate this on 1.21, not on 1.14, because the alternative has not been in place on any 1.14 release yet 
2. Wait with depreciation until these alternatives have actually been tested in the field.

2021-09-12 18:49 UTC, patricklodder requested changes
NAK. Cannot depreciate this on 1.14 because there is no alternative.

For this to turn into an ACK, the following has to happen:
1. Actually have the alternative `createauxblock` and `submitauxblock` in place
2. Have documentation that explains how to implement these
3. Have tested this, fully integrated and provable, in the field, on `testnet3` or equivalent. With for example Litecoin testnet, but preferably other chains too.
4. Have positive feedback from miners that run it on `mainnet` and all known concerns addressed.

Note that until then, I will have to NAK this for 1.21 too.

2021-09-14 17:01 UTC, patricklodder commented
@chromatic do you mind if we close this? I feel that it's not going to be useful on 1.14.5 even if we would bring back the alternative RPC methods right now.

2021-09-14 18:03 UTC, chromatic commented
@patricklodder Absolutely! I think we should do two more things:

 * add your review criteria to the issue that prompted this PR
 * document a deprecation strategy

I'm happy to do both, though I recognize that the latter needs discussion and thinking and it won't necessarily be a quick process.

2021-09-15 13:15 UTC, patricklodder commented
I noted the list of requirements in the issue. For the plan, we can start the discussion there or using discussions. I don't mind either way.

I'm closing this PR.

2021-09-15 13:15 UTC, closed without merging