docs: update macos build guide
dogecoin/dogecoin pull request #2686
Opened 2021-11-08 17:25 UTC by patricklodder

This takes @michilumin's macOS build guide that was originally created for 1.14.2 and makes it the default macOS guide. 

### Changes:

- Removes the boost source compile, no longer needed since #1655
- Formats to be closer to the other build guides
- Remove $-signs in front of commands, to make it easier to c&p
- Replaces the old build-osx guide because that is unmaintained and this one is better
- Now tested on Big Sur 11.3

I meant to pull this into 1.14.5 but I must have forgotten to create the actual PR... 😣

2021-12-01 18:52 UTC, patricklodder commented
Have some findings on the M1 build for this, will adapt. See also #2245.

2021-12-18 00:21 UTC, patricklodder commented
Since #2745 fixes some of this guide, I will adapt this after that PR is merged.

2022-03-22 02:00 UTC, CryptoUnchained approved these changes

2022-07-15 18:45 UTC, patricklodder commented
Just spent hours trying to get this to work on an x86_64 and an arm64 mac with 12.4 - neither works. Same situation as a couple of months ago with 12.1. The only way to make db5.3 compilation succeed is by using `--enable-posixmutexes` and that makes the software throw the panic code at runtime:

```
ERROR: CDBEnv::Open: Error -30973 opening database environment: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
```

even on an empty directory.

I currently do not have a solution for building on 12.x and I don't have any hardware with 11.x as I upgraded both MacBooks to be able to test 12.x, so I'm kind of stuck until I find the right patch for db5.3 and cannot deliver this guide for 1.14.6. I'm moving the target for this to 1.14.7.

2023-03-03 14:20 UTC, 0xShremp commented
i had to add `--enable-posixmutexes` to the configuration of berkeley-db or it would fail with `configure: error: Support for FCNTL mutexes was removed in BDB 4.8.`

2023-09-26 19:24 UTC, michilumin commented
reviewing in re following with #3308

2023-09-26 21:26 UTC, michilumin commented
So as of right now still having bdb detection issues when using the default berkeley-db brew keg. This was on a "pristine" osx intel env.  Intentionally skipping the Oracle pull and build, of course.  More to come.

2023-10-28 13:50 UTC, patricklodder commented
Updated to reflect changes since #3308

2024-02-11 23:05 UTC, FierceSkit commented on doc/build-macos.md
> +             qt5 zeromq qrencode librsvg boost berkeydb@5
Should be: qt5 zeromq qrencode librsvg boost berkeley-db@5

2024-02-11 23:23 UTC, FierceSkit commented on doc/build-macos.md
> +**NOTE:** If you have Xcode installed, simply zip it up and move it for this
NOTE not needed - it apparently works regardless

2024-02-11 23:25 UTC, FierceSkit commented on doc/build-macos.md
> +/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
instead: git clone https://github.com/Homebrew/brew homebrew

2024-02-11 23:26 UTC, FierceSkit commented on doc/build-macos.md
> +/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
addendum:
```sh
eval "$(homebrew/bin/brew shellenv)"
brew update --force --quiet
chmod -R go-w "$(brew --prefix)/share/zsh"
```

2024-02-12 00:53 UTC, FierceSkit commented
[config.log.zip](https://github.com/dogecoin/dogecoin/files/14234632/config.log.zip)

2024-02-12 01:06 UTC, patricklodder commented
> config.log.zip

Thanks! This means:

- install `protobuf@21` because abseil from @25 does not like how we use protobuf (to be deprecated) and thus requires `-std=c++17` and @22-@24 requires `-std=c++14`
- `brew link protobuf@21`

I can repro the build with these steps.

2024-02-12 01:12 UTC, patricklodder commented
@michilumin this updated version of the guide removes issues with protobuf and c++ standards it requires and fixes some typos. Please let me know if this resolves your issues.

2024-02-13 00:12 UTC, FierceSkit commented
Tested this multiple times -> working on 14.3.1 & 14.4.1

2024-02-13 23:44 UTC, michilumin commented
Process of testing this now from *clean* Sonoma 14.2.1; will say that during the process it will *appear* to hang even on fast machines.  (Process looks OK for now just... lengthy.) Leaving this note here for any future builders to be warned. 

Suggestion to just add the -v flag to the brew install steps so the enduser doesn't think things are locked up, and if Brew does fail for some reason it's less likely to fail silently. 

Will have this verified shortly.

2024-02-14 00:56 UTC, michilumin commented
Ok, for this to work for me, I did have to include the (previously included) cppflag path exports after bdb5 build:

```
export LDFLAGS="-L/Users/(USER_DIR)/(BUILD_DIR)/homebrew/opt/berkeley-db@5/lib"
export CPPFLAGS="-I/Users/(USER_DIR/(BUILD_DIR)/homebrew/opt/berkeley-db@5/include"
```

Pretty sure this is because the package (bdb 5) is considered an alternate vs a default that exists on MacOS. 

Suggest after the prereqs install step and right before the step that asks  you to cd into the /dogecoin dir, 

```
export LDFLAGS="-L$(pwd)/homebrew/opt/berkeley-db@5/lib"
export CPPFLAGS="-I$(pwd)/homebrew/opt/berkeley-db@5/include"
```

Will suggest those in the doc.

2024-02-14 00:59 UTC, michilumin commented on doc/build-macos.md
> +
Set the linker and c flags to let the compiler know where to find bdb db@5:

```sh
export LDFLAGS="-L$(pwd)/homebrew/opt/berkeley-db@5/lib"
export CPPFLAGS="-I$(pwd)/hombrew/opt/berkeley-db@5/include"

2024-02-14 01:01 UTC, michilumin commented on doc/build-macos.md
> +brew install autoconf automake libtool miniupnpc openssl pkg-config protobuf@21 \
Suggest ```brew install -v autoconf ... ...``` since the process can appear to freeze for long periods of time without the verbose flag.

2024-02-14 01:02 UTC, michilumin requested changes
ACK, successful build 14.2.1 with 1 nit (verbosity) and one minor path step.

2024-02-14 06:09 UTC, michilumin approved these changes
All OK, ACK and good to go.

2024-02-14 15:01 UTC, patricklodder commented
Still had 2 'squashme' annotated commits, so I squashed these.

2024-02-17 19:12 UTC, chromatic approved these changes
I reviewed the pre- and post-squash commits and all is good. Ditto ACK.

2024-02-18 21:37 UTC, merged