Set the wallet's discard threshold to 0.01 DOGE
dogecoin/dogecoin pull request #2964
Opened 2022-05-25 03:12 UTC by matheusbach

At this point, of the 1203 nodes online, 752 of them are already running version 1.14.5 or higher (62.5%), which means that the hard and soft dust limit are already widely adopted and, in my view, it is safe to update the discart threshold of 1 DOGE to 0.01 DOGE.

I've already tested sending a value equal to 0.01 DOGE paying only a small fee, without the dust penalty, and I was successful.

2022-05-25 03:28 UTC, SparK-Cruz approved these changes
Looks good to me

2022-05-25 15:11 UTC, patricklodder commented
Thank you! I too noticed an uptick in miner upgrades lately, so my gut says this is reasonable.

I will run & document a bigger test on mainnet to validate that the network is ready for this. I've marked this "do not merge" until we have some definite insights, getting these shouldn't have to take too long.

2022-05-27 21:41 UTC, patricklodder commented
While I was creating my analytics, I noticed that someone has been testing dust limits before I could, so thank you for saving me 0.1 DOGE, whoever you are ❤️😁

All current easily identifiable major mining pools support outputs < 1 DOGE now. Proof:

- [DMr3fE...](https://sochain.com/block/DOGE/12b88033a2d0eb8186c99b663812880a5779068f663879ca61e6550a50bb4696) 386/2000 blocks
- [DQvuJB...](https://sochain.com/block/DOGE/b4996639e9e753513b55e96a2a3f57c9102e9688c14beebaf7ef525e18f6cf26) 298/2000 blocks
- [DMqRVL...](https://sochain.com/block/DOGE/b3ab53414dd32edcb207fd6cc0b7138f0bf27020d5b4f9078616432aa291f9ea) 266/2000 blocks
- [DHFu8W...](https://sochain.com/block/DOGE/46030e0137ec8411566b5061dc4c6332106375484b9242e30e94101c43400fa8) 214/2000 blocks
- [DTZSTX...](https://sochain.com/block/DOGE/a5edcd50c8251eb6573852ca741db194e2bc5eb089954ed514af19823d8033bc) 128/2000 blocks

So that's about 65% of the hash power represented across these pools at the moment of writing.

Concept ACK from me. I'll do a separate code review to help getting this PR to a mergeable state.

2022-05-27 21:46 UTC, patricklodder requested changes
1. Please revert the changes to the manpages. We generate those right before release using `help2man`.
2. Some of the tests fail, so you'll need to fix these. For this change, I think it would be acceptable if we were to copy the original https://github.com/dogecoin/dogecoin/blob/6fd30245b442a9a3a2f6480586809bcfb816a1a1/src/wallet/test/wallet_tests.cpp#L543 and insert it once more between lines 526 and 527, but keep your edit to the new line 543 too. This way, the unit test stays useful and we decouple testing functions from whatever the default values are. If we feel we need to expand the test, we can do so separately.

Everything else, big fat ✅ from me. Thank you!

2022-05-28 17:02 UTC, matheusbach commented
I reverted the changes to the man pages as requested.

I also tried to correct the tests, but I have no experience with unit tests, so I don't know if I did it correctly

2022-05-28 21:07 UTC, patricklodder commented
The automated tests are now good, and actually improved: unit tests (in `src/test`) now test the functions, and integration tests (in `qa/rpc-tests`) test the parametrization. 

This looks pretty good now - I'm moving on to test UI for this.

2022-05-29 00:22 UTC, matheusbach commented
I have just retested with varying values but greater than 0.01. It worked perfectly

[37953185...](https://dogechain.info/tx/37953185018fa9e22290b74b527fb3d495d4496914587257d06890c041b07479)

452 outputs, just 0.15 DOGE transaction fee. The community will love

2022-05-29 00:36 UTC, chromatic commented
I scanned the rest of the code for anything else that might need modified, but this PR seems to cover everything. Concept ACK from me, and no concerns about implementation at the code level.

2022-06-18 21:15 UTC, chromatic commented
@matheusbach Are you comfortable squashing this into a single commit? We have [squashing directions](https://github.com/dogecoin/dogecoin/blob/master/CONTRIBUTING.md#squashing-commits) in the contributing guide and we're happy to help however we can.

2022-06-24 01:24 UTC, matheusbach commented
squash done

2022-06-24 02:34 UTC, patricklodder approved these changes
tested ACK - on Ubuntu focal and macOS Monterey (M1)

2022-06-25 14:28 UTC, merged