Adding a few french translation
dogecoin/dogecoin pull request #3123
Opened 2022-09-30 19:20 UTC by omahs

very commit

2022-09-30 19:44 UTC, patricklodder commented
Thank you! 

I've added `help wanted` because this needs native speaker review.

2022-10-18 21:37 UTC, patricklodder commented
Tagging recent French-speaking contributors: @thisiskeanyvy @martyornot @jadehamel @daank-c

Would you have a moment to glance over these newly translated sentences? Would be much appreciated and wow.

2022-10-18 22:37 UTC, daank-c commented
@patricklodder, do the string translations in `bitcoin_fr.ts` become the fallback values if the `bitcoin_fr_CA.ts` translations aren't up-to-date?

2022-10-18 22:52 UTC, patricklodder commented
> do the string translations in bitcoin_fr.ts become the fallback values if the bitcoin_fr_CA.ts translations aren't up-to-date?

No. `bitcoin_fr_CA.ts` has been unmaintained since day 1 and when we discussed this here on the repo at the end of the last release cycle, the general idea was that we do not update it because it's a lot of double work and use `bitcoin_fr.ts` instead to cover both.

I was planning to propose to delete it for this release - together with every other unmaintained variant - because for `fr` and `fr_CA`, the written language is (as I was told) very much alike - so we can make one really good translation that (presumably) suites all. If that is not the case and there are significant differences, then we can keep it of course, but we should realize that it's double the maintenance work.

2022-10-19 00:57 UTC, daank-c commented
> I was planning to propose to delete it for this release - together with every other unmaintained variant - because for `fr` and `fr_CA`, the written language is (as I was told) very much alike

Oh right, thanks for the reminder. Derp

Ok, so these translations were done with a free online translator and make very little sense. I can write the proper translations as a review, or just do it in a different pull-request, up to you.

2022-10-19 04:28 UTC, thisiskeanyvy commented on src/qt/locale/bitcoin_fr.ts
>          <translation type="unfinished"></translation>
Celui qui possède les clés privées, possède les pièces

2022-10-19 04:34 UTC, thisiskeanyvy requested changes
One translation to be added and another to be modified for a more correct French otherwise everything is ok for me

2022-10-19 04:34 UTC, thisiskeanyvy commented on src/qt/locale/bitcoin_fr.ts
>          <translation type="unfinished"></translation>
Compléter par "Celui qui possède les clés privées, possède les pièces"

2022-10-19 04:34 UTC, thisiskeanyvy commented on src/qt/locale/bitcoin_fr.ts
> +        <translation>Pour suivre le développement en cours et contribuer, consultez le repo Dogecoin Core sur GitHub.</translation>
Corriger "repo" du mot anglais repository par "dépôt" qui est plus correct en français, "Pour suivre le développement en cours et contribuer, consultez le dépôt Dogecoin Core sur GitHub."

2022-10-19 04:37 UTC, thisiskeanyvy commented on src/qt/locale/bitcoin_fr.ts
> +        <translation>Pour suivre le développement en cours et contribuer, consultez le repo Dogecoin Core sur GitHub.</translation>
Line 1502 can also be completed with "Celui qui possède les clés privées, possède les pièces"

2022-10-19 06:24 UTC, omahs commented
@thisiskeanyvy just updated according to your comments

2022-10-19 12:35 UTC, patricklodder commented
First off: thanks everyone - you're awesome.

> I can write the proper translations as a review, or just do it in a different pull-request, up to you.

It's really up to you. I would say that if you have additional comments on top of Keany's review, let's just have them here first. If you don't like the result after that, you can always open your own pull request - improvements are always welcome.

2022-10-19 13:06 UTC, thisiskeanyvy commented
Would you mind squashing this into a single commit? Then I can approve it, all good to me otherwise.

Feel free to reach out if you'd like any assistance with the squashing. @omahs

2022-10-19 13:44 UTC, thisiskeanyvy commented
Use this command to group your commits into one. "git rebase -i HEAD~5" @omahs

2022-10-19 14:21 UTC, closed without merging

2022-10-19 14:41 UTC, patricklodder commented
Note: this is now moved to #3148