qa: update ltc_scrypt installation script and documentation
dogecoin/dogecoin pull request #3147
Opened 2022-10-18 18:40 UTC by xanimo

-per 3afaf90 our test framework requires ltc_scrypt as found on [L26](https://github.com/dogecoin/dogecoin/blob/1.21-dev/test/functional/test_framework/messages.py#L26) of test/functional/test_framework/messages.py, therefore i've updated the install-deps script to use v1.0.1 and added script invocation instructions on the test dirs README.md.

2022-10-19 10:41 UTC, patricklodder requested changes
Tested this on a clean minimal jammy. If not using depends, we don't need curl for successful compilation.

Therefore, when walking through doc/build-unix.md, we get compiled binaries, but then this installer fails because nowhere in the process did we install curl. I think it should be mentioned here.

2022-10-19 10:41 UTC, patricklodder commented on test/README.md
> +`ltc_scrypt` is required. On an OS with `python3`, `python3-pip` and `python3-setuptools` it can be installed via:
also need `curl`

2022-10-19 20:09 UTC, xanimo commented on test/README.md
> +`ltc_scrypt` is required. On an OS with `python3`, `python3-pip` and `python3-setuptools` it can be installed via:
Done :+1:

2022-10-21 19:22 UTC, patricklodder approved these changes
ACK - tested on Ubuntu 22.04

2022-10-26 07:50 UTC, merged