Translation and addition of the README.md file in French (README_fr_FR.md)
dogecoin/dogecoin pull request #3194
Opened 2023-01-01 00:09 UTC by thisiskeanyvy

- Addition of a README_fr_FR.md file based on translations of the README.md file with understandable French
- Cross-reference other translated README files with this one (on line 14 in README.md, README_zh_CN.md, README_pt_BR.md and README_fa_IR.md)

2023-01-01 00:11 UTC, thisiskeanyvy commented
Happy New Year 2023 to the whole community! 🥳

2023-01-04 20:07 UTC, thisiskeanyvy commented
Conflict resolution with the version 1.14.7-dev branch

2023-02-09 17:45 UTC, thisiskeanyvy commented
Final commit with squash of all the others.

2023-05-19 14:00 UTC, Martyornot reviewed
Encore une fois, un excellent travail @thisiskeanyvy. La seule chose que j'ai pu remarquer concerne l'utilisation de "pair-a-pair". Je sais pas si c'est mieux de laisser la notion "peer-to-peer" qui semble plus utilisée. Mais c'est clairement un détail.

2023-05-19 14:00 UTC, Martyornot commented on README_fr_FR.md
> +Dogecoin Core utilise par défaut le port `22556` pour la communication pair-à-pair qui est nécessaire pour synchroniser la blockchain au "mainnet" et rester informé des nouvelles transactions et bloc
Peut-être laisser "peer-to-peer" au lieu de "pair-à-pair".

2023-05-19 20:54 UTC, thisiskeanyvy commented on README_fr_FR.md
> +Dogecoin Core utilise par défaut le port `22556` pour la communication pair-à-pair qui est nécessaire pour synchroniser la blockchain au "mainnet" et rester informé des nouvelles transactions et bloc
Je propose qu'on garde pair-à-pair et qu'on standardise une bonne fois pour toute pour éviter de le changer à nouveau tous les ans.

2023-05-19 20:55 UTC, thisiskeanyvy commented
@Martyornot Merci beaucoup à toi pour la review ! :)

2024-02-19 21:35 UTC, thisiskeanyvy commented
I accidentally squashed one too many commits.

2024-02-19 21:52 UTC, thisiskeanyvy commented
How can I restore this commit without affecting the last commit?

2024-02-19 22:02 UTC, patricklodder commented
> How can I restore this commit without affecting the last commit?

The easiest way is to do `git rebase -i 1.14.7-dev` and then comment out any extra commits (but pick the last commit)

2024-02-20 16:23 UTC, patricklodder commented
Since this in its current state would overwrite links to the Vietnamese README, and I think we need to think up a better solution for this due to high growth of translated READMEs, I want to come up with a better maintainable solution for the next release, as we should also find a means to accommodate dialect READMEs, like `pt_PT` next to `pt_BR`.

I'm going to park this PR for the next release (either 1.14.8 or 1.15.0, depending on the outcome of #3418).

2024-02-20 21:11 UTC, patricklodder commented
I've written a problem statement and proposal to fix re: those readme files in #3436

2024-06-26 11:02 UTC, patricklodder commented
Please rewrite this to the new structure introduced by #3459 and it can go in.

2024-06-27 18:50 UTC, thisiskeanyvy commented
Hi @patricklodder, I've migrated the French README.md files to the new structure, thanks for letting me know!

- Addition of a README_fr_FR.md,README_fr_CA.md files based on translations of the README.md file with understandable French
- Use of the new doc/intl structure in version 1.15.0-dev

2024-06-27 19:29 UTC, patricklodder requested changes
Currently this changes 287 files - so it needs a rebase to clean that up. Let me know if you need me to help with that.

2024-06-27 20:40 UTC, thisiskeanyvy commented
> Currently this changes 287 files - so it needs a rebase to clean that up. Let me know if you need me to help with that.

Sorry, I didn't realise, thank you very much! Normally it's fine now and for minor corrections in the translation file I'll open a new pull request.

2024-06-27 21:54 UTC, patricklodder requested changes
I checked that the version with @Martyornot's comments was the same as this version, and that is the case, so this doesn't need language review per-se. That part is covered.

Some minor administrative things:

- `fr_CA` version is 100% the same as `fr_FR` - let's just keep one version (`fr_FR` or just `fr`, up to you), to reduce maintenance burden. The generic `fr` has seen more reviewers than `fr_CA` too.
- Cross-links should be removed.
- Recommend renaming the file itself to just be `README.md`, i.e. make the path `doc/intl/fr_FR/README.md`
- Need to add links in `doc/intl/README.md`

2024-06-27 21:54 UTC, patricklodder commented on doc/intl/fr_FR/README_fr_FR.md
> +
This needs to be removed.

2024-06-27 21:54 UTC, Martyornot approved these changes
Si c'est juste pour review le README_fr_FR & README_fr_CA, c'est correct. Si tu as besoin d'une review complète des trads pour le Core, dis-moi. :)

2024-06-27 22:00 UTC, Martyornot commented
If needed, I could do a review of the CA version and make it a little more French-Canadian. But ultimately, it would be like 95% the fr_FR version. Probably not very useful.

2024-06-27 22:09 UTC, thisiskeanyvy commented
Many thanks to you both @patricklodder and @Martyornot ! I've finally removed the CA version, but if there's a need a Canadian contributor will add it and change the path from fr to fr_FR if there's a real need for a different version.

2024-06-27 22:10 UTC, patricklodder approved these changes
ACK - language checked by @Martyornot

2024-06-27 22:29 UTC, patricklodder commented
> If needed, I could do a review of the CA version and make it a little more French-Canadian. But ultimately, it would be like 95% of the fr_FR version. Probably not very useful.

There's a proposal for a `fr_CA` version in #3279. Once this PR goes in (in 24h if there are no objections) it would be easy to refactor that one too. We can pick that up there, if it's really desired. I'm okay with having an `fr_CA` too if people want it now that we have a structure that doesn't clog the root directory. It does create double the work every time the readme changes, which I expect to happen more often now; we've been slowly changing development process over the years.

2024-06-29 14:30 UTC, merged