doc : add French translation of README and crosslink readmes
dogecoin/dogecoin pull request #3279
Opened 2023-06-17 18:48 UTC by sinetek

Very baguette much woof. I've added a bit of silly words and the language is french from canada.

2023-06-17 19:06 UTC, sinetek commented
also pls gib salmon:  DJAde1A8VWbZwQU3WofUqNB7XP4FZSu2ji

2023-06-25 22:19 UTC, bitcoinfinancier approved these changes

2023-07-05 08:56 UTC, thisiskeanyvy commented
Pull request already opened for the French README (duplication of pull request #3194)

2023-08-07 02:09 UTC, John-Inubook reviewed
To automatically translate the Dogecoin repository's README from English to French using the Google Translate API, you can use the googletrans library. Here's a simplified example script:


from github import Github
from googletrans import Translator

# Replace with your GitHub token
GITHUB_TOKEN = "YOUR_GITHUB_TOKEN"

# Repository information
OWNER = "dogecoin"
REPO = "dogecoin"
README_FILE = "README.md"

# Initialize GitHub API client
github = Github(GITHUB_TOKEN)

# Get the repository
repo = github.get_repo(f"{OWNER}/{REPO}")

# Get the README content
readme = repo.get_contents(README_FILE)
readme_content = readme.decoded_content.decode("utf-8")

# Translate English text to French
def translate_to_french(text):
    translator = Translator()
    translated_text = translator.translate(text, src="en", dest="fr")
    return translated_text.text

# Translate the README content
translated_content = translate_to_french(readme_content)

# Create a new branch for the translation
new_branch = repo.create_git_ref("refs/heads/translate-readme", repo.get_branch("main").commit.sha)

# Update the README content in the new branch
repo.update_file(README_FILE, "Translate README to French", translated_content, readme.sha, branch="translate-readme")

print("README translation and update successful.")
In this example, you would need to install the github library using pip install PyGithub and the googletrans library using pip install googletrans==4.0.0-rc1. Replace "YOUR_GITHUB_TOKEN" with your actual GitHub API token.

Please be aware that automatically translating content can sometimes result in inaccuracies or unintended phrasing due to limitations of machine translation. It's a good practice to review the translated content and make necessary adjustments after the script runs.

2024-01-06 08:12 UTC, philipperemy commented
Hi, I'm french from France. and there's a couple of typo like `Séléction`, `discutter`. Are the typos made on purpose?

2024-01-06 08:22 UTC, thisiskeanyvy commented
> Hi, I'm french from France. and there's a couple of typo like `Séléction`, `discutter`. Are the typos made on purpose?

Je pense qu'il a juste utilisé un traducteur automatique et que celui-ci a eu quelques difficultés à traduire. 

De plus, j'ai déjà fait une traduction en français pour le readme (FR-fr qui logiquement devrait être le même pour Fr-ca) voici la référence vers la pull request faite plus tôt et déjà review #3194.

2024-02-09 18:06 UTC, John-Inubook commented
Merci pour votre aide, je ne suis pas un dev et j'ai simplement voulu essayé quelque chose. Désolé si je vous ai fait perdre votre temps.
Vous pouvez supprimer ce que j'ai fait si c'est plus simple.
Bonne continuation.

2024-02-19 20:48 UTC, thisiskeanyvy commented
> Merci pour votre aide, je ne suis pas un dev et j'ai simplement voulu essayé quelque chose. Désolé si je vous ai fait perdre votre temps. Vous pouvez supprimer ce que j'ai fait si c'est plus simple. Bonne continuation.

Au contraire c'est très bien d'essayer, Dogecoin c'est avant tout la communauté, vous pouvez garder votre commit, l'améliorer puis attendre une approbation. Il y a également d'autres versions qui ont besoin de contributeurs comme la version CA.

2024-06-29 21:39 UTC, patricklodder commented
If a Canadian version is still desirable now that we have a French version of the readme, please refactor this into the new structure introduced by #3459, without cross-links.

2024-07-01 18:10 UTC, jadehamel commented on README_fr_CA.md
> +Séléction de la langue: [EN](./README.md) | [CN](./README_zh_CN.md) | [PT](./README_pt_BR.md) | [FA](./README_fa_IR.md)  | [VI](./README_vi_VN.md) | FR
Typo in "Séléction". Correct spelling is "Sélection".

2024-07-01 18:10 UTC, jadehamel commented on README_fr_CA.md
> +Pour plus d'information sur les frais de transaction sur le réseau Dogecoin, veuillez consulter l'addresse:
Typo in "addresse". Correct spelling is "adresse".

2024-07-01 18:12 UTC, jadehamel commented on README_fr_CA.md
> +### Trop ports
Typo in "Trop ports". Correct spelling is "Ports"

2024-07-01 18:12 UTC, jadehamel commented on README_fr_CA.md
> +Dogecoin Core est un programme en logiciel libre géré par la communauté. Le processus de développement est ouvert et visible publiquement; tout le monde peut voir, discutter et travailler sur le prog
Typo in "discutter". Correct spelling is "discuter".

2024-07-01 18:13 UTC, jadehamel commented on README_fr_CA.md
> +Nos resources principales de développement :
Typo in "resources". Correct spelling is "ressources".

2024-07-01 18:14 UTC, jadehamel commented on README_fr_CA.md
> +Si vous trouvez un bogue ou avez une expérience inhabituelle avec ce programme, veuillez nous le signaler en utilisant le [traqueur de bogue](https://github.com/dogecoin/dogecoin/issues/new?assignees
"traqueur de bogue" is acceptable, but "rapport de bug" is more commonly used

2024-07-01 18:15 UTC, jadehamel commented on README_fr_CA.md
> +Ayez la gentilesse de lire [](https://github.com/dogecoin/dogecoin/blob/master/CONTRIBUTING.md) pour apprendre comment contribuer au développement de Dogecoin Core. Il y a souvent des [questions ouve
The link for "lire" is missing a URL.

2024-07-01 18:15 UTC, jadehamel commented on README_fr_CA.md
> +
Typo in "ce passe". Correct spelling is "se passe".

2024-07-01 18:16 UTC, jadehamel commented on README_fr_CA.md
> +Dogecoin Core est disponible sous les termes de la licence MIT. Veuillez-voir [COPYING](COPYING) pour plus d'information ou [opensource.org](https://opensource.org/licenses/MIT)
Typo in "Veuillez-voir". Correct spelling is "Veuillez voir".

2024-07-01 19:41 UTC, jadehamel commented
> If a Canadian version is still desirable now that we have a French version of the readme, please refactor this into the new structure introduced by #3459, without cross-links.

As a french Canadian, my opion about this is given the project scope and audience, implementing French Canadian translations isn't necessary. Our content primarily targets a global French-speaking audience without specific regional nuances or legal compliance needs for Quebec. Since we're focusing on general information dissemination rather than localized marketing or regulatory requirements, a standard French translation will effectively cater to our audience's needs worldwide.

2025-03-03 10:24 UTC, thisiskeanyvy commented
Anyone got any news on this pull request? It has not been modified since it was opened. I think it would be consistent to close it if no changes are made. (It is obsolete compared to the current versions on the repo)

2025-03-03 10:42 UTC, thisiskeanyvy requested changes
The pull request needs to be updated.

2025-03-03 13:03 UTC, philmb3487 commented
Can close, nobody cares.

2025-03-03 18:43 UTC, philmb3487 commented
D'accord merci tout le monde pour la correction et pardon d'avoir fait trâiner le paquet !
Il y a une traduction fr-ca officielle maintenant à saveure locale ?

2025-03-03 22:07 UTC, philmb3487 commented
Super je vais fermer le fil.

2025-03-03 22:07 UTC, closed without merging