Minor update bitcoin_ko_KR.ts
dogecoin/dogecoin pull request #3430
Opened 2024-02-18 23:26 UTC by FultonDoge

not a programmer, unable to test run the results of my translation
translated new? untranslated lines 1773, 1779, 2761, 4573, 4577, i dont believe there are any more untranslated lines
in the case of line 2761 reused identical line 2737 translation with minor update to replace satoshi with koinu for 2761 translation and both to make more sense.
assumed for line 4573 that %s and %i would print as %s and %i instead of being replaced by a string or integer

2024-02-18 23:34 UTC, slightlyskepticalpotat commented
Yeah, as far as I know `%s` and `%i` are supposed to stay in translations everywhere. The "linter" check checks if your translations are syntactically correct and will fail if you miss a quote or anything.
![image](https://github.com/dogecoin/dogecoin/assets/31290848/c6aeaf10-f08b-467f-921e-3beea28599bf)

2024-02-19 00:52 UTC, patricklodder commented
Added help wanted. If someone that speaks Korean could give a quick glance, that'd be awesome.

2024-02-19 06:24 UTC, ilsubyeega commented on src/qt/locale/bitcoin_ko_KR.ts
> +        <translation>지갑 트랜잭션 변화시 명령 실행 (명령 안의 %s는 TxID, %i 는 블록높이로 변경되며 트랜잭션이 더 이상 chaintip 안이 아닌 경우에는 0으로 대체된다)</translation>
```suggestion
        <translation>지갑 트랜잭션 변화시 명령 실행 (명령 안의 %s는 TxID, %i 는 블록높이로 변경되며 트랜잭션이 더 이상 chaintip 안이 아닌 경우에는 0으로 대체됩니다.)</translation>
```

2024-02-19 06:26 UTC, ilsubyeega commented on src/qt/locale/bitcoin_ko_KR.ts
> +        <translation>해당 기능 사용시 매우 주의하기 바랍니다</translation>
For me, `the sentence` in the source above doesn't look translated into `translation`.

2024-02-19 06:27 UTC, ilsubyeega commented on src/qt/locale/bitcoin_ko_KR.ts
> +        <translation>해당 기능 사용시 매우 주의하기 바랍니다</translation>
Other this ^, `the sentence` in the source above doesn't look translated into `translation`, as it's three sentences.

2024-02-19 08:07 UTC, ilsubyeega commented on src/qt/locale/bitcoin_ko_KR.ts
> +        <translation>BIP70 지불 요청은 지원 종료 되었으며 기본적으로 비활성화 되어 있습니다. 꼭 해당 기능 이용해야 한다면 -enable-bip70 이용하여 재시작하기 바랍니다.
뒷 문장이 어색해 보입니다. 제가 암호화페에 대하여 자세히는 모르지만 -enable-bip70은 옵션/파라미터로 보여지는데 `~을 이용하여` 보단 `~와 함께`거나 `~ 옵션을 추가해` 와 같은 문구가 어울릴 것 같습니다.

2024-02-19 08:07 UTC, ilsubyeega commented on src/qt/locale/bitcoin_ko_KR.ts
> +        <translation>Payment request file handling은 기본적으로 비활성화 되어 있습니다. 꼭 해당 기능 이용해야 한다면 -enable-bip70 이용하여 재시작하기 바랍니다.
Payment request file handling은 해당 번역 파일에 `지불 요청 파일 처리` 로 번역되어 있으니, 이점 참고하시면 좋을 것 같습ㄴ다.

2024-02-19 08:22 UTC, ilsubyeega requested changes

2024-02-19 08:22 UTC, ilsubyeega commented on src/qt/locale/bitcoin_ko_KR.ts
> +        <translation>BIP-70 PaymentServer 활성화</translation>
```suggestion
        <translation>BIP-70 PaymentServer 활성화 (기본값: 0)</translation>
```

2024-02-19 19:16 UTC, ilsubyeega approved these changes

2024-02-19 22:26 UTC, patricklodder approved these changes
ACK - code reviewed.

Language validated and corrected by @ilsubyeega

2024-02-21 00:10 UTC, merged