Added pt_PT Readme
dogecoin/dogecoin pull request #3565
Opened 2024-06-27 14:41 UTC by qlpqlp

Added pt_PT Readme

2024-06-27 15:53 UTC, patricklodder commented
Added `help wanted` -> needs a sanity check by a native speaker.

2024-06-27 21:01 UTC, vhs94 requested changes
Nice work! 🎉 just added a few small typos fixes and suggestions

2024-06-27 21:01 UTC, vhs94 commented on doc/intl/pt_PT/README.md
> +*por favor, encaminhem novos recursos na ramificação de desenvolvimento com a versão mais alta.*
not trying to be picky with the `atualização` but just wanted to throw a light on it to keep consistency with line 32 `"actualizadas"`

```suggestion
- **master:** Estável, contém a ultima versão da ultima actualização principal *major.minor*.
- **maintenance:** Estável, contém a ultima versão de actualizações anteriores, que ainda estão em manutenção. Formato: ```<version>-maint```
- **development:** Instável, contém código novo para actualizações planeadas. Formato: ```<version>-dev```

*As ramificações Master e Maintenance, são exclusivamente mutáveis por lançamento. Actualizações*
*planeadas terão sempre uma ramificação de desenvolvimento e as solicitações de inclusão deverão ser*
*encaminhadas por meio destas. Ramificações de manutenção existem apenas para **correção de bugs,***
*por favor, encaminhem novos recursos na ramificação de desenvolvimento com a versão mais alta.*
```

2024-06-28 09:06 UTC, qlpqlp commented on doc/intl/pt_PT/README.md
> +* [Projetos do Github](https://github.com/dogecoin/dogecoin/projects) é utilizado para conduzir trabalhos planeado ou que estejam em desenvolvimento para as próximas atualizações.
In this case, the word "actualizações" do the the new Portuguese spelling agreement its "atualizações" without the "c"

http://www.portaldalinguaportuguesa.org/?action=novoacordo&act=list&version=pe
https://www.dge.mec.pt/acordo-ortografico

Is that OK with you?

2024-06-28 09:36 UTC, vhs94 commented on doc/intl/pt_PT/README.md
> +* [Projetos do Github](https://github.com/dogecoin/dogecoin/projects) é utilizado para conduzir trabalhos planeado ou que estejam em desenvolvimento para as próximas atualizações.
@qlpqlp yep! totally fine, but then probably it's better to change like 32 

` e se manter actualizadas` > ` e se manter atualizadas` to keep consistency, right?

2024-06-28 09:37 UTC, vhs94 commented on doc/intl/pt_PT/README.md
> +*por favor, encaminhem novos recursos na ramificação de desenvolvimento com a versão mais alta.*
yep! even better actually, good job :)

2024-07-09 21:39 UTC, qlpqlp commented
@vhs94 can you review again if everything is OK in your end? :)
Much thanks in advance :)

2024-07-10 18:33 UTC, vhs94 approved these changes

2024-07-10 18:34 UTC, vhs94 commented
> @vhs94 can you review again if everything is OK in your end? :) Much thanks in advance :)

looking fine from my side, approved 💯  🥇

2024-07-10 22:33 UTC, patricklodder approved these changes
utACK - language review was done by @vhs94

2024-07-13 01:37 UTC, merged