German README.md
dogecoin/dogecoin pull request #3622
Opened 2024-08-10 03:12 UTC by FierceSkit

Added a German README.md, since there'd been important changes lately.
Please Read & Review - any Suggestions, aswell as Corrections welcome.

2024-08-10 13:09 UTC, patricklodder commented
Added `help wanted` -> needs a native speaker to review.

2024-08-10 19:04 UTC, loom4k requested changes
I would change a couple of things, mainly spelling mistakes and incorrect capitalization. Overall a really good translation.

2024-08-10 19:04 UTC, loom4k commented on doc/intl/de_GER/README.md
> +Dogecoin Core verwendet den Port `22556` als Standart-Port zur Kommunkation
```suggestion
Dogecoin Core verwendet den Port 22556 als Standardport zur Kommunikation
```

Changed "Standart-Port" to "Standardport" and "Kommunkation" to "Kommunikation" for correct spelling.

2024-08-10 19:04 UTC, loom4k commented on doc/intl/de_GER/README.md
> +Zusätzlich kann ein JSONRPC Port geöffnet werden, welcher den Port `22555` als Standartport für Mainnet Nodes verwendet.
```suggestion
Zusätzlich kann ein JSON-RPC-Port geöffnet werden, der den Port 22555 als Standardport für Mainnet-Nodes verwendet.
```

Added hyphens for "JSON-RPC-Port" and "Mainnet-Nodes" to match German compound noun formatting.

2024-08-10 19:04 UTC, loom4k commented on doc/intl/de_GER/README.md
> +**Es wird STRENGSTENS davon abgeraten RPC Ports im öffentlichen Internet Sichtbar zu machen!**
```suggestion
**Es wird dringend davon abgeraten, RPC-Ports im öffentlichen Internet sichtbar zu machen!**
```

Changed "STRENGSTENS" to "dringend" for a more typical expression and corrected "Sichtbar" to "sichtbar."

2024-08-10 19:04 UTC, loom4k commented on doc/intl/de_GER/README.md
> +Dogecoin Core ist eine Open-Source Software und wird von der Community entwickelt.
```suggestion
Dogecoin Core ist eine Open-Source-Software und wird von der Community entwickelt.
```

Added a hyphen to "Open-Source-Software" for correct compound noun formatting.

2024-08-10 19:04 UTC, loom4k commented on doc/intl/de_GER/README.md
> +Der Entwicklungsprozess ist transparent und öffentlich Einsehbar; Jeder kann ihn sehen, darüber diskutieren und daran teilhaben!
```suggestion
Der Entwicklungsprozess ist transparent und öffentlich einsehbar; jeder kann ihn sehen, darüber diskutieren und daran teilhaben!
```

Lowercased "Einsehbar" to "einsehbar" and "Jeder" to "jeder" for consistency in capitalization.

2024-08-10 19:04 UTC, loom4k commented on doc/intl/de_GER/README.md
> +Die Vergabe der Versionsnummern efolgt nach dem Prinzip von ```major.minor.patch```.
```suggestion
Die Vergabe der Versionsnummern erfolgt nach dem Prinzip von ```major.minor.patch```.
```

Corrected "efolgt" to "erfolgt".

2024-08-10 19:04 UTC, loom4k commented on doc/intl/de_GER/README.md
> +Es gibt 4 Arten von "Branches" in diesem Repository:
```suggestion
Es gibt 4 Arten von Branches in diesem Repository:
```

Removed quotation marks around "Branches" for consistency.

2024-08-10 19:04 UTC, loom4k commented on doc/intl/de_GER/README.md
> +Wenn Sie an der Mithilfe oder der Entwicklung von Dogecoin Core interessiert sind sehen Sie sich Bitte den [Beitragsleitfaden](CONTRIBUTING.md) an.
```suggestion
Wenn Sie an der Mithilfe oder der Entwicklung von Dogecoin Core interessiert sind, sehen Sie sich bitte den [Beitragsleitfaden](CONTRIBUTING.md) an.
```

Added a comma and lowercased "Bitte" for correct punctuation and consistency.

2024-08-10 19:04 UTC, loom4k commented on doc/intl/de_GER/README.md
> +Vielleicht findet sich ja auch Jemand, der Ihnen bei ihren Projekten behilflich sein kann.
```suggestion
Vielleicht findet sich ja auch jemand, der Ihnen bei Ihren Projekten behilflich sein kann.
```

Lowercased "Jemand" and changed "ihren" to "Ihren" to match the capitalization and case correctly.

2024-08-10 21:25 UTC, loom4k commented on doc/intl/de_GER/README.md
> +Es gibt 4 Arten von "Branches" in diesem Repository:
Sounds good to me. Let's keep it as you had it.

2024-08-10 21:26 UTC, loom4k commented on doc/intl/de_GER/README.md
> +Dogecoin Core verwendet den Port `22556` als Standart-Port zur Kommunkation
I made a typo in my suggestion and forgot to add the back braces. That's on me. Definitely keep it as `22556`.

2024-08-10 21:27 UTC, loom4k commented on doc/intl/de_GER/README.md
> +Zusätzlich kann ein JSONRPC Port geöffnet werden, welcher den Port `22555` als Standartport für Mainnet Nodes verwendet.
Again, typo on my side for the back quotation marks.

2024-08-10 21:27 UTC, loom4k commented on doc/intl/de_GER/README.md
> +**Es wird STRENGSTENS davon abgeraten RPC Ports im öffentlichen Internet Sichtbar zu machen!**
No problem with that. Let's keep it as you had it 👍

2024-08-10 21:28 UTC, loom4k commented
Looks all good to me.

2024-08-10 21:29 UTC, loom4k approved these changes
Looks all good to me.

2024-08-10 21:44 UTC, loom4k commented
Absolutely. I will do this as soon as I get home. Might be a couple of hours however. Will leave a CR ASAP.

2024-08-11 01:39 UTC, loom4k approved these changes
This looks all good on my side. Great translation work by @FierceSkit! @patricklodder I'd say that's a wrap. This would be ready to merge when you are 😉

2024-08-11 06:00 UTC, loom4k commented
No problem. I didn't think of leaving it open but it's actually a great idea. I'm so used of being in a rush. Let's see what others think!

2024-08-11 06:50 UTC, DGalapagos8 commented on doc/intl/de_GER/README.md
> +Herzlich sind sie Eingeladen sich umzusehen um neue Leute kennenzulernen, die neueste Memes zu teilen, um Hilfe anzubieten oder auch zu erhalten und an Diskussionen teilzuhaben.
```suggestion
Herzlich sind sie Eingeladen sich umzusehen um neue Leute kennenzulernen, die neuesten Memes zu teilen, um Hilfe anzubieten oder auch zu erhalten und an Diskussionen teilzuhaben.
```
Changed singular to plural.

2024-08-11 07:41 UTC, DGalapagos8 commented on doc/intl/de_GER/README.md
> +Herzlich sind sie Eingeladen sich umzusehen um neue Leute kennenzulernen, die neuesten Memes zu teilen, um Hilfe anzubieten oder auch zu erhalten und an Diskussionen teilzuhaben.
```suggestion
Herzlich sind Sie eingeladen sich umzusehen um neue Leute kennenzulernen, die neuesten Memes zu teilen, um Hilfe anzubieten oder auch zu erhalten und an Diskussionen teilzuhaben.
```
Spelling.

2024-09-10 22:58 UTC, DGalapagos8 approved these changes
looks good to me.

2024-09-10 23:06 UTC, DGalapagos8 requested changes

2024-09-10 23:06 UTC, DGalapagos8 commented on doc/intl/de_GER/README.md
> +- **development:** Intabil, enthält neuen Code für kommende Versionen. Format: ```<version>-dev```
```suggestion
- **development:** Instabil, enthält neuen Code für kommende Versionen. Format: ```<version>-dev```
```

2024-09-11 07:23 UTC, DGalapagos8 commented on doc/intl/de_GER/README.md
> +mit dem Peer-to-Peer Netzwerk und um die "Mainnet" Blockchain zu Synchronisieren.
```suggestion
mit dem Peer-to-Peer Netzwerk und um die "Mainnet" Blockchain zu synchronisieren.
```

2024-09-11 07:37 UTC, DGalapagos8 requested changes
Those are the last things I found. spelling and grammer.

2024-09-11 07:37 UTC, DGalapagos8 commented on doc/intl/de_GER/README.md
> +Dogecoin Core verwendet den Port `22556` als Standart-Port zur Kommunkation
```suggestion
Dogecoin Core verwendet den Port `22556` als Standart-Port zur Kommunikation
```

2024-09-11 15:30 UTC, DGalapagos8 approved these changes
I totally approve this.

2024-09-11 21:09 UTC, patricklodder commented
I'll squash this for you.

2024-09-11 21:25 UTC, patricklodder approved these changes
utACK. This still needs integration with the index in `doc/intl/README.md`, but that could be done separately too.

Since I squashed this, needs a second ACK from another maintainer.

2024-09-12 22:02 UTC, michilumin approved these changes
Drawing on my German grom growing up in a weird school where it was spoken primarily -- LGTM. :)

2024-10-01 12:08 UTC, merged