Optimize IPC Server Name Handling
dogecoin/dogecoin pull request #3637
Opened 2024-08-30 20:07 UTC by jimjimmiejames

- Update IPC Server Name handling to QFile so random hashing can be preserved, prioritize attempts to open instances, and generate new sockets if new server is initialized
- Moves debug handler up for IPC URI/Initialize visibility
- Removes unused PaymentServer bip70 arguments
- NOTE: contains patricklodder::1.15.0-remove-bip70 branch (Sorry I didn't isolate my changes! I'm still learning Git!)

2024-08-31 01:37 UTC, chromatic commented
Writing to the file system seems a little heavy-handed. Would somethin glike this be simpler and just as effective?

```
diff --git a/src/qt/paymentserver.cpp b/src/qt/paymentserver.cpp
index 2d870a451..b37a14b79 100644
--- a/src/qt/paymentserver.cpp
+++ b/src/qt/paymentserver.cpp
@@ -75,7 +75,7 @@ namespace // Anon namespace
 //  testnet / non-testnet
 //  data directory
 //
-static QString ipcServerName()
+static QString _ipcServerName()
 {
     QString name("DogecoinQt");
 
@@ -88,6 +88,12 @@ static QString ipcServerName()
     return name;
 }
 
+static QString ipcServerName()
+{
+    static QString ipcServerName = _ipcServerName();
+    return ipcServerName;
+}
+
 //
 // We store payment URIs and requests received before
 // the main GUI window is up and ready to ask the user
```

I think to test this we'd want some debugging information in the unmodified code to display the random int, data dir, and resulting hash on any call to `ipcServerName()` -- that would help track down if there are multiple calls or order of operation concerns or (as I'm starting to worry now) threading differences in the current implementation.

2024-08-31 02:40 UTC, jimjimmiejames commented
Not sure I understand this solution, are you storing a static string once rather than calling the function elsewhere? 
Multiple calls of the ipcServerName() within each launch all result in one server name. However each URI click opens a new instance which issues a new name.

2024-08-31 04:06 UTC, jimjimmiejames commented
Removing the rand INT will solve the problem; but I left it because AFAIK it was introduced to account for crashes providing unique server names each instance.

The problem is, storing the server name in a QString (with rand INT) leaves the same issue:
1. Boot
2. Generate rand INT > Hash server name
3. Attempt to connect socket to that name
4. Fail/False > Initialize new server (given name from step 2)
5. URI click repeats step 1

I debugged the server name within the ipcServerName() function, & it is consistent within one run, but as soon as you click a new link, that is where it falls apart.

The reason I went server-name.txt is only for "file open" check on the attempt to connect to server which accounts for crash + rand INT, but open to other ideas.

2024-09-09 18:08 UTC, chromatic commented
I've been thinking about this and want to pitch a different angle of attack; I think randomization may be fine but the problem is that Windows wants to launch more than one instance of the Core. If we can find a way to use a single-instance mutex somehow, we may solve this and other problems.

I don't know Windows well enough to be certain about this approach. It needs research or insight.

2024-09-09 18:18 UTC, jimjimmiejames commented
I will drop this PR and isolate my changes in main branch with just paymentserver updates, I had two ideas: local file (obviously not ideal) _or_ QT's SharedMemory inclusion which I can take a stab at..

2024-09-09 18:22 UTC, patricklodder commented
Custom `QSharedMemory` may also need a lot of security hardening so be aware that that too could become dangerous, quickly. Make sure your expectation is "slow and maximally painful review", and if you can live with that then by all means propose... it's always good to consider alternatives.

2024-09-09 18:28 UTC, chromatic commented
It wouldn't surprise me if Qt had an os-independent mutex we could use here. I'd rather review our use of that than invent something new.

2024-09-09 18:37 UTC, jimjimmiejames commented
potentially exposing memory security holes is not the first-step I want to take into contributing at this point 😂
I'm not sure how else I can help other than hopefully getting closer to pinpointing the actual issue here.

2024-09-09 22:18 UTC, jimjimmiejames commented
thoughts on QSystemSemaphore as mutex without reaching into memory/storage, putting it in launch order-of-operation in the IPC send/initialize sequence?
https://doc.qt.io/qt-5/qsystemsemaphore.html

2024-09-10 01:39 UTC, chromatic commented
That might work. Somewhere in the back of my mind I remember a Windows programming pattern where there can only be one instance of a program running at a time. I'm not sure if the Qt system semaphore supports this. We may need a Windows expert to help.

2024-09-10 15:22 UTC, patricklodder commented
If you have 2 datadirs, which one should get the request from a link click? Honestly makes no sense to me 🤔

2024-09-10 18:26 UTC, jimjimmiejames commented
the datadir is set in each QT instance, and Windows Registry chooses which QT to launch URIs. So it'll pick whatever is in dogecoin/shell/command URI handler, and if that one is not open it'll launch; if it is, it'll attempt to send to the existing instance but again (root problem) failing due to socket not found rand INT server name hash.

2024-09-10 18:50 UTC, patricklodder commented
I meant that conceptually it kind of breaks when you have 2 datadirs.

2024-09-10 18:57 UTC, jimjimmiejames commented
Ah yes 🤣 well I've been deep in just the URI piece only so far

2024-11-09 09:17 UTC, MrPiNkY2022 approved these changes

2024-11-11 05:06 UTC, jimjimmiejames commented
Isolated my changes w/ #3689 so we can close this one

2024-11-11 05:07 UTC, closed without merging

2025-03-23 04:12 UTC, MrPiNkY2022 requested changes
Try rewriting some of the code

2025-03-23 04:12 UTC, MrPiNkY2022 commented on src/qt/bitcoin.cpp
> -#include "fs.h"
Fix this

2025-03-23 04:12 UTC, MrPiNkY2022 commented on src/qt/paymentserver.h
> -#include "paymentrequestplus.h"
Fix this